### ISSUE TITLE
OpenCV Error: Unspecified error (The node is neither a map nor an empty collection) 

### ISSUE THREAD

**Issue by punnu97** [ITCoders/Human-detection-and-Tracking#25] opened 2018-01-15 08:20 UTC
OpenCV Error: Unspecified error (The node is neither a map nor an empty collection) in cvGetFileNodeByName, file C:\projects\opencv-python\opencv\modules\core\src\persistence.cpp, line 891
Traceback (most recent call last):
  File "main.py", line 137, in <module>
    recognizer.read("model.yaml")          
cv2.error: C:\projects\opencv-python\opencv\modules\core\src\persistence.cpp:891: error: (-2) The node is neither a map nor an empty collection in function cvGetFileNodeByName

Earlier there was ' recognizer.load("model.yaml") ' in the original code but there is no attribute 'load' attribute in new version of current  opencv which has been replaced by 'read'.

**Comment by prsntmaurya** [comment] 2018-01-16 04:23
Hi Purnima,
Can you specify the OpenCV version you are using now?

**Comment by punnu97** [comment] 2018-01-16 07:55
Hello,
Yes, it is OpenCV version 3.4.0 and Python version 3.6.4

**Comment by prsntmaurya** [comment] 2018-01-16 10:05
Hi Purnima,
Please run the following command on your python console and share the results with me.
1.   help(cv2.face.createLBPHFaceRecognizer().read)
2.   help(cv2.face.createLBPHFaceRecognizer().load)

**Comment by prsntmaurya** [comment] 2018-01-16 10:40
Hi Purnima,
I got the fix for this issue. The issue is due to model.yaml file, you have to create new yaml file using the script "create_face_model.py". Please follow the steps below before running "create_face_model.py":
1. Change line no 12:  `recognizer = cv2.face.createLBPHFaceRecognizer()`   to 
 `recognizer = cv2.face.LBPHFaceRecognizer_create()`
2. Change line no. 62:  `recognizer.save("cont.yaml")`   to 
`recognizer.save("model.yaml")`

After this run "create_face_model.py" using command: `python3 create_face_model.py -i data/` 
please note that `data/` is the directory where you have put training images. You can replace the images in that directory with new dataset following the name convention mentioned in **Readme** file.

After that, you can run `main.py`.

**Comment by punnu97** [comment] 2018-01-16 11:18
Hi Prashant,

Thanks a lot for your help! My issue is resolved now.

**Comment by prsntmaurya** [comment] 2018-01-16 12:40
I am closing the issue.

**Closed as completed by prsntmaurya** 2018-01-16 12:40 UTC
Labels: version_conflict
